{
  parserClass = "com.msan.ngxformatidea.grammar.dump.NgxParser"
//  extends = "com.intellij.lang.parser.GeneratedParserUtilBase"
  extends = "com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Ngx"
  psiImplClassSuffix="Impl"
  psiPackage="com.msan.ngxformatidea.psi"
  psiImplPackage="com.msan.ngxformatidea.psi.impl"

  elementTypeHolderClass="com.msan.ngxformatidea.psi.NgxTypes"
  elementTypeClass="com.msan.ngxformatidea.psi.NgxElementType"
  tokenTypeClass="com.msan.ngxformatidea.psi.NgxTokenType"

  tokens = [
//    COMPONENT_START = "[component]"
//    COMPONENT_END = "[/component]"
//    TEXT = "regexp:[^\[$\\\s]+"
//    LINE_COMMENT = "//[^\\n]*"  // Single-line comment
//    BLOCK_COMMENT = "/\\*[^*]*\\*/"  // Multi-line comment
//    WHITE_SPACE = "regexp:[^\S\n]+"
  ]
}

//file ::= (component | TEXT | LINE_COMMENT | WHITE_SPACE)*
file ::= component*

component ::= COMPONENT_START content* COMPONENT_END  { pin=1 }
//component ::= "[component]" | "regexp:(.*)" | "[/component]"  { pin=1 }

//content ::= TEXT { pin=1 }
//content ::= ("[^\\[\\]\\n\\r]+" | WHITE_SPACE | LINE_COMMENT)+ { pin=1 }
content ::= TEXT | WHITE_SPACE | LINE_TERMINATOR { pin=1 }
//content ::=  WHITE_SPACE | LINE_TERMINATOR { pin=1 }
comment ::= LINE_COMMENT
//text ::= TEXT

//LINE_TERMINATOR ::= "\r|\n|\r\n"
LINE_TERMINATOR ::= "regexp:(\r?\n)+"
//LINE_TERMINATOR ::= "[ \t\f]"
COMPONENT_START ::= "[component]"
COMPONENT_END ::= "[/component]"
//TEXT ::= "regexp:[^\\[\\]\\n\\r]+"
//TEXT ::= "[^\\[\\]\\n\\r]+"
//TEXT ::= "regexp:[^\r\n]"
//TEXT ::= "regexp:[^\[$\\\s]+"
//TEXT ::= "regexp:[^\[$\\\s]+"
//TEXT ::= "regexp:[^\[$\\\s]+"
WHITE_SPACE ::= "regexp:\\s+"
LINE_COMMENT ::= "regexp://[^\\n]*"
//NEWLINE ::= "regexp:(\r?\n)+"

//BLOCK_COMMENT ::= "/\\*([^*]|\\*+[^*/])*\\*+/"
//COMPONENT ::= "[component]" (TEXT | TEXT | WHITE_SPACE | LINE_COMMENT | BLOCK_COMMENT)* "[/component]"


//comment ::= LINE_COMMENT | BLOCK_COMMENT

// Define token names
//tokens {
//  COMPONENT_START = "[component]"
//  COMPONENT_END = "[/component]"
//  TEXT = "[^\\[\\]]+"
//  WHITE_SPACE = "\\s+"
//}

//tokens {
//  COMPONENT_START = "\\[component\\]"
//  COMPONENT_END = "\\[/component\\]"
//  TEXT = "[^\\[\\]\\n\\r]+"
//  WHITESPACE = "\\s+"
//  LINE_COMMENT = "//[^\\n]*"
//  BLOCK_COMMENT = "/\\*([^*]|\\*+[^*/])*\\*+/"
//}