{
  parserClass = "com.msan.ngxformatidea.parser.NgxParser"
  extends = "com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Ngx"
  psiImplClassSuffix="Impl"
  psiPackage="com.msan.ngxformatidea.psi"
  psiImplPackage="com.msan.ngxformatidea.psi.impl"

  elementTypeHolderClass="com.msan.ngxformatidea.psi.NgxTypes"
  elementTypeClass="com.msan.ngxformatidea.psi.NgxElementType"
  tokenTypeClass="com.msan.ngxformatidea.psi.NgxTokenType"

  // Everything not used below that should be a token
  tokens = [
    "WHITE_SPACE";
  ]
}

file ::= (template | style | component | WHITE_SPACE)*
template ::= TEMPLATE_START (TEMPLATE_CONTENT)* TEMPLATE_END { mixin="com.msan.ngxformatidea.psi.impl.NgxComponentMixin" }
style ::= STYLE_START (STYLE_CONTENT)* STYLE_END { mixin="com.msan.ngxformatidea.psi.impl.NgxComponentMixin" }
component ::= COMPONENT_START (COMPONENT_CONTENT)* COMPONENT_END { mixin="com.msan.ngxformatidea.psi.impl.NgxComponentMixin" }
ts_element ::= TS_EXPRESSION | TS_STATEMENT


//file ::= (template | style | component | WHITE_SPACE)*
//template ::= TEMPLATE_START (TEMPLATE_CONTENT)* TEMPLATE_END {pid 1}
//style ::= STYLE_START (STYLE_CONTENT)* STYLE_END {pid 1}
//component ::= COMPONENT_START (COMPONENT_CONTENT)* COMPONENT_END {pid 1}
//ts_element ::= TS_EXPRESSION | TS_STATEMENT


