{
  parserClass = "com.msan.ngxformatidea.parser.NgxParser"
  extends = "com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Ngx"
  psiImplClassSuffix="Impl"
  psiPackage="com.msan.ngxformatidea.psi"
  psiImplPackage="com.msan.ngxformatidea.psi.impl"

  elementTypeHolderClass="com.msan.ngxformatidea.psi.NgxTypes"
  elementTypeClass="com.msan.ngxformatidea.psi.NgxElementType"
  tokenTypeClass="com.msan.ngxformatidea.psi.NgxTokenType"

  // Everything not used below that should be a token
  tokens = [
    "WHITE_SPACE";
  ]
}

//file ::= (TEMPLATE_START | STYLE_START | COMPONENT_START | WHITE_SPACE)*


//template ::= TEMPLATE_START (TEMPLATE_CONTENT)* TEMPLATE_END { mixin="com.msan.ngxformatidea.psi.impl.NgxComponentMixin" }
//style ::= STYLE_START (STYLE_CONTENT)* STYLE_END { mixin="com.msan.ngxformatidea.psi.impl.NgxComponentMixin" }
//component ::= COMPONENT_START (COMPONENT_CONTENT)* COMPONENT_END { mixin="com.msan.ngxformatidea.psi.impl.NgxComponentMixin" }

file ::= (template | style | component | WHITE_SPACE)*
template ::= TEMPLATE_BLOCK { mixin="com.msan.ngxformatidea.psi.impl.NgxTemplateMixin" }
style ::= STYLE_BLOCK { mixin="com.msan.ngxformatidea.psi.impl.NgxStyleMixin" }
component ::= COMPONENT_BLOCK{ mixin="com.msan.ngxformatidea.psi.impl.NgxComponentMixin" }